import { TableSchemaMap } from "../types/schemaConfig";

export const tableSchemas: TableSchemaMap = {
  Recipe: [
    { key: "recipeId", header: "Recipe ID", type: "input" },
    { key: "recipeTitle", header: "Recipe Title", type: "input" },
    { key: "recipeVersion", header: "Recipe Version", type: "input" },
    { key: "recipeType", header: "Recipe Type", type: "input" },
    { key: "product", header: "Product", type: "input" },
    { key: "description", header: "Description", type: "input" },
    { key: "approvedDate", header: "Approved Date", type: "input" },
  ],
  MonitoringPoints: [
    { key: "monitoredValue", header: "MONITORED VALUE", type: "input" },
    { key: "docId", header: "DOC_ID (FK)", type: "input" },
    { key: "unitOperation", header: "UNIT OPERATION", type: "input" },
    { key: "monitoringPoint", header: "MONITORING POINT", type: "input" },
    { key: "createdBy", header: "CREATED BY", type: "input" },
    { key: "createdAt", header: "CREATED AT", type: "input" },
  ],
  UnitOperations: [
    { key: "unitOperationName", header: "UNIT OPERATION NAME", type: "input" },
    { key: "unitOperationType", header: "UNIT OPERATION TYPE", type: "input" },
    {
      key: "unitOperationSequence",
      header: "UNIT OPERATION SEQUENCE",
      type: "input",
    },
    {
      key: "unitOperationDescription",
      header: "UNIT OPERATION DESCRIPTION",
      type: "input",
    },
    { key: "docId", header: "DOC_ID (FK)", type: "input" },
    {
      key: "unitOperationComment",
      header: "UNIT OPERATION COMMENT",
      type: "input",
    },
    { key: "createdBy", header: "CREATED BY", type: "input" },
    { key: "createdAt", header: "CREATED AT", type: "input" },
  ],
  Activity: [
    { key: "activityName", header: "ACTIVITY NAME", type: "input" },
    { key: "unitOperationId", header: "UNIT OPERATION ID (FK)", type: "input" },
    { key: "activitySequence", header: "ACTIVITY SEQUENCE", type: "input" },
    {
      key: "activityDescription",
      header: "ACTIVITY DESCRIPTION",
      type: "input",
    },
    { key: "commentType", header: "COMMENT TYPE", type: "input" },
    { key: "commentText", header: "COMMENT TEXT", type: "input" },
    { key: "docId", header: "DOC_ID (FK)", type: "input" },
    { key: "runId", header: "RUN ID (FK)", type: "input" },
    { key: "createdBy", header: "CREATED BY", type: "input" },
    { key: "createdAt", header: "CREATED AT", type: "input" },
  ],
  Parameters: [
    { key: "parameterName", header: "PARAMETER NAME", type: "input" },
    { key: "unitOperationId", header: "UNIT OPERATION ID (FK)", type: "input" },
    { key: "activityId", header: "ACTIVITY ID (FK)", type: "input" },
    { key: "targetValue", header: "TARGET VALUE", type: "input" },
    { key: "rangeMin", header: "ACCEPTABLE RANGE MIN", type: "input" },
    { key: "rangeMax", header: "ACCEPTABLE RANGE MAX", type: "input" },
    { key: "docId", header: "DOC_ID (FK)", type: "input" },
    { key: "createdBy", header: "CREATED BY", type: "input" },
    { key: "createdAt", header: "CREATED AT", type: "input" },
  ],
  Material: [
    { key: "materialName", header: "MATERIAL NAME", type: "input" },
    { key: "docId", header: "DOC_ID (FK)", type: "input" },
    { key: "totalQuantity", header: "TOTAL QUANTITY", type: "input" },
    { key: "materialUOM", header: "MATERIAL UOM", type: "input" },
    { key: "bomComment", header: "BOM COMMENT", type: "input" },
    { key: "runId", header: "RUN ID (FK)", type: "input" },
    { key: "createdBy", header: "CREATED BY", type: "input" },
    { key: "createdAt", header: "CREATED AT", type: "input" },
  ],
};
